name: aeyepetizer
description: A eyetipzer Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  json_annotation: 4.5.0
  http: 0.13.4
  cached_network_image: 3.2.1

  dio: 4.0.6
  pull_to_refresh: 2.0.0

  provider: 6.0.2
  flutter_ijkplayer: 0.3.5+1

  flutter_base:
    #git:
    #  url: 'https://github.com/archko/flutter_base.git'
    #  ref: 'dev_1.5_androidx'
    path: ../flutter_base/

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 6.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
